version: '2'

services:
  web:
    build:
        context: .
        dockerfile: 'Dockerfile.dev'
    container_name: web_dev
    ports:
     - "80:80"
     - "3000:3000"
     - "3001:3001"
     - "3002:3002"
    volumes:
     - ./src:/src
